In [1]:
import pandas as pd
from pathlib import Path
import pyarrow.parquet as pq

### Read table

In [2]:
# Define root folder
PROJECT_ROOT= Path.cwd().parent
# Khai báo đường dẫn liệu
DATA_DIR= PROJECT_ROOT/"data"/"raw"

PARQUET_PATH=DATA_DIR/"yellow_tripdata_2026-01.parquet"
LOOKUP_PATH=DATA_DIR/"taxi_zone_lookup.csv"

# Kiểm tra file tồn tại
print("Project root: ",PROJECT_ROOT)
print("Parquet exists: ",PARQUET_PATH.exists())
print("Lookup exists: ",LOOKUP_PATH.exists())

Project root:  c:\Users\Acer\Documents\DATA ANALYST\Portfolio\NYC Taxi Project
Parquet exists:  True
Lookup exists:  True

In [6]:
df=pd.read_parquet(PARQUET_PATH)
zones= pd.read_csv(LOOKUP_PATH)
display(df.head(10))
display(zones.head(10))

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee,cbd_congestion_fee
0,2,2026-01-01 00:54:04,2026-01-01 00:59:37,1.0,0.97,1.0,N,239,238,1,7.2,1.00,0.5,3.66,0.0,1.0,15.86,2.5,0.0,0.00
1,1,2026-01-01 00:34:04,2026-01-01 00:39:47,0.0,0.90,1.0,N,163,162,2,7.9,4.25,0.5,0.00,0.0,1.0,13.65,2.5,0.0,0.75
2,1,2026-01-01 00:57:06,2026-01-01 01:05:59,0.0,1.40,1.0,N,43,237,1,10.7,4.25,0.5,2.50,0.0,1.0,18.95,2.5,0.0,0.75
3,2,2026-01-01 00:15:22,2026-01-01 00:58:10,4.0,5.58,1.0,N,142,209,1,38.7,1.00,0.5,11.11,0.0,1.0,55.56,2.5,0.0,0.75
4,2,2026-01-01 00:27:13,2026-01-01 00:40:43,0.0,2.16,1.0,N,88,144,1,13.5,1.00,0.5,3.85,0.0,1.0,23.10,2.5,0.0,0.75
5,2,2026-01-01 00:47:11,2026-01-01 01:00:47,2.0,2.33,1.0,N,144,137,1,14.2,1.00,0.5,4.99,0.0,1.0,24.94,2.5,0.0,0.75
6,1,2026-01-01 00:17:54,2026-01-01 00:28:32,1.0,1.30,1.0,N,142,50,2,11.4,4.25,0.5,0.00,0.0,1.0,17.15,2.5,0.0,0.75
7,1,2026-01-01 00:34:28,2026-01-01 00:59:05,0.0,2.90,1.0,N,50,234,1,22.6,4.25,0.5,5.65,0.0,1.0,34.00,2.5,0.0,0.75
8,2,2026-01-01 00:34:14,2026-01-01 01:11:58,1.0,5.34,1.0,N,161,45,1,37.3,1.00,0.5,8.61,0.0,1.0,51.66,2.5,0.0,0.75
9,2,2026-01-01 00:41:07,2026-01-01 00:50:42,3.0,1.83,1.0,N,237,263,1,10.7,1.00,0.5,2.36,0.0,1.0,18.06,2.5,0.0,0.00

   LocationID        Borough                     Zone service_zone
0           1            EWR           Newark Airport          EWR
1           2         Queens              Jamaica Bay    Boro Zone
2           3          Bronx  Allerton/Pelham Gardens    Boro Zone
3           4      Manhattan            Alphabet City  Yellow Zone
4           5  Staten Island            Arden Heights    Boro Zone
5           6  Staten Island  Arrochar/Fort Wadsworth    Boro Zone
6           7         Queens                  Astoria    Boro Zone
7           8         Queens             Astoria Park    Boro Zone
8           9         Queens               Auburndale    Boro Zone
9          10         Queens             Baisley Park    Boro Zone

### Kiểm tra cấu trúc dữ liệu

In [9]:
print("Taxi data shape", df.shape)
print("Zone lookup shape",zones.shape)

Taxi data shape (3724889, 20)
Zone lookup shape (265, 4)

In [10]:
df.describe().T

,count,mean,min,25%,50%,75%,max,std
VendorID,3724889.0,1.873598,1.0,2.0,2.0,2.0,7.0,0.701458
tpep_pickup_datetime,3724889,2026-01-17 01:44:52.106518,2025-12-31 23:57:29,2026-01-09 17:51:59,2026-01-16 21:20:56,2026-01-24 07:25:11,2026-02-01 00:45:01,NaN
tpep_dropoff_datetime,3724889,2026-01-17 02:02:03.696138,2025-12-31 23:57:32,2026-01-09 18:08:47,2026-01-16 21:36:14,2026-01-24 07:40:22,2026-02-01 23:35:31,NaN
passenger_count,2636831.0,1.256271,0.0,1.0,1.0,1.0,9.0,0.670243
trip_distance,3724889.0,6.455647,0.0,1.0,1.81,3.73,269097.48,648.885528
RatecodeID,2636831.0,5.218853,1.0,1.0,1.0,1.0,99.0,19.653699
PULocationID,3724889.0,161.43719,1.0,114.0,161.0,233.0,265.0,67.066574
DOLocationID,3724889.0,160.99357,1.0,107.0,162.0,234.0,265.0,71.03604
payment_type,3724889.0,0.846564,0.0,0.0,1.0,1.0,4.0,0.712049
fare_amount,3724889.0,20.804254,-2555.2,10.0,15.6,26.1,2555.2,18.927007
extra,3724889.0,1.023055,-7.5,0.0,0.0,2.5,17.46,1.707322
mta_tax,3724889.0,0.483377,-0.5,0.5,0.5,0.5,4.75,0.114556
tip_amount,3724889.0,2.608142,-88.88,0.0,2.0,3.71,766.0,3.917405
tolls_amount,3724889.0,0.498375,-94.5,0.0,0.0,0.0,122.22,2.131731
improvement_surcharge,3724889.0,0.947913,-1.0,1.0,1.0,1.0,1.0,0.265486
total_amount,3724889.0,29.178526,-2560.2,17.0,23.05,33.83,2560.2,22.58553
congestion_surcharge,2636831.0,2.15487,-2.5,2.5,2.5,2.5,2.5,0.942365
Airport_fee,2636831.0,0.148294,-1.75,0.0,0.0,0.0,26.75,0.533671
cbd_congestion_fee,3724889.0,0.519644,-0.75,0.0,0.75,0.75,0.75,0.35681

Nhận định về dữ liệu ban đâu:

`passenger_count`: Min = 0, max = 9	Có giá trị 0 và số lượng hành khách bất thường cần kiểm tra

`trip_distance`: Min = 0, max = 269.097,48 Có chuyến 0 dặm và giá trị cực lớn; có thể ảnh hưởng trung bình

`fare_amount`L Min= -2555.2 max = 2.555,2 Có thể gồm giao dịch điều chỉnh hoặc hoàn tiền

`extra, mta_tax`: Có giá trị âm Cần kiểm tra quy tắc ghi nhận và giao dịch điều chỉnh

`tip_amount` :Min = -88,88; max = 766 Giá trị âm hoặc rất lớn cần kiểm tra

`tolls_amount` :Min = -94,5; max = 122,22 Cần xác định có phải điều chỉnh cước hay không

`total_amount` :Min = -2.560,2; max = 2.560,2 Cần kiểm tra tính hợp lý và cách tính tổng

`RatecodeID` :Max = 99 Có mã cần đối chiếu tài liệu dữ liệu

In [19]:
# Kiểm tra giá trị null
showDFnull=df.isnull().sum()
showZNnull=zones.isnull().sum()
print(f"Giá trị null \n{showDFnull[showDFnull>0]}\n")
print(f"Giá trị Zones null \n{showZNnull[showZNnull>0]}")

Giá trị null
passenger_count         1088058
RatecodeID              1088058
store_and_fwd_flag      1088058
congestion_surcharge    1088058
Airport_fee             1088058
dtype: int64

Giá trị Zones null
Borough         1
Zone            1
service_zone    2
dtype: int64

In [21]:
# Kiểm tra giá trị trùng lặp
showDFdup=df.duplicated().sum()
showZNdup=zones.duplicated().sum()
print(f"Giá trị trùng lặp taxi trip \n{showDFdup}\n")
print(f"Giá trị trùng lặp Zones \n{showZNdup}")

Giá trị trùng lặp taxi trip
0

Giá trị trùng lặp Zones
0